edition = "2018"
use_field_init_shorthand = true
use_try_shorthand = true
fn_single_line = true
imports_granularity = "Crate"
match_arm_blocks = true
max_width = 80
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
