// Copyright takubokudori.
// This source code is licensed under the MIT or Apache-2.0 license.
pub mod errhandlingapi;
pub mod fileapi;
pub mod handleapi;
pub mod ioapiset;
pub mod jobapi;
pub mod jobapi2;
pub mod libloaderapi;
pub mod memoryapi;
pub mod minwinbase;
pub mod namedpipeapi;
pub mod processenv;
pub mod processthreadsapi;
pub mod stringapiset;
pub mod synchapi;
pub mod timezoneapi;
pub mod tlhelp32;
pub mod winbase;
pub mod winnt;
pub mod winreg;
pub mod winuser;
pub mod winver;
pub mod wow64apiset;
